export const SELLER_APPLICATION_ADD = "SELLER_APPLICATION_ADD";
export const SELLER_APPLICATION_SET_ALL = "SELLER_APPLICATION_SET_ALL";
export const SELLER_APPLICATION_REVIEW = "SELLER_APPLICATION_REVIEW";
